// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBsKuFMjXxS0JcHKeD6Z_dDt-_Uslb_uBw',
    appId: '1:386141162163:web:362f04c95f0d0e41babec6',
    messagingSenderId: '386141162163',
    projectId: 'learning-flutter-z2410',
    authDomain: 'learning-flutter-z2410.firebaseapp.com',
    storageBucket: 'learning-flutter-z2410.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD5J6BLXPVQ5Twu8vY_yia08gCLSgKgoo4',
    appId: '1:386141162163:android:01bb8ab65513d1f5babec6',
    messagingSenderId: '386141162163',
    projectId: 'learning-flutter-z2410',
    storageBucket: 'learning-flutter-z2410.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAmaiKrTs498iz3eQzPWh4UU0AaMIcSKz8',
    appId: '1:386141162163:ios:3b2340dbb7c1d4eababec6',
    messagingSenderId: '386141162163',
    projectId: 'learning-flutter-z2410',
    storageBucket: 'learning-flutter-z2410.appspot.com',
    iosClientId: '386141162163-on4nfldk9q3m25ff3u4um485j9eq6fi6.apps.googleusercontent.com',
    iosBundleId: 'com.example.flutterCodelab',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAmaiKrTs498iz3eQzPWh4UU0AaMIcSKz8',
    appId: '1:386141162163:ios:359bf6b5bc3972f5babec6',
    messagingSenderId: '386141162163',
    projectId: 'learning-flutter-z2410',
    storageBucket: 'learning-flutter-z2410.appspot.com',
    iosClientId: '386141162163-lrstv5iseuabpj22333vdjiogfac4m1m.apps.googleusercontent.com',
    iosBundleId: 'com.example.flutterCodelab.RunnerTests',
  );
}
